Repository GSG-G11/Ramadan-Plan, pull requests merged in 2022-03, with the labels that each got.

#6 create react app
  package.json
  ramadan-plan/.gitignore
  ramadan-plan/README.md
  ramadan-plan/package-lock.json
  ramadan-plan/package.json
  ramadan-plan/public/index.html
  ramadan-plan/public/manifest.json
  ramadan-plan/public/robots.txt
  ramadan-plan/src/App.css
  ramadan-plan/src/App.js
  ramadan-plan/src/index.css
  ramadan-plan/src/index.js
Labels: Awaiting Review, Done

#7 Create App Component with style
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  ramadan-plan/README.md
  ramadan-plan/package-lock.json
  ramadan-plan/package.json
  ramadan-plan/src/App.css
  ramadan-plan/src/App.js
  ramadan-plan/src/index.css
  src/App.css
  src/App.jsx
  src/Ramadan-Background.jpg
  src/index.css
  src/index.js
Labels: Awaiting Review

#11 handle add plan
  public/index.html
  src/App.css
  src/App.jsx
  src/Components/Card.jsx
  src/Components/TextAreaComponent.jsx
Labels: Awaiting Review

#12 add delete function
  src/App.jsx
  src/Components/Card.jsx
Labels: In Progress

#18 15 readme
  README.md
Labels: Awaiting Review
